### ISSUE TITLE
Versioning of child elements

### ISSUE THREAD

**Issue by aureliusm** [mpociot/versionable#5]
Hi,

can you please help me how to setup versioning for child model in various relationships.

For example, I have a model "Page" and another model "PageWidget" which has a page_id field. I would like to init versioning of PageWidget when I version Page model and keep the connection.

I am willing to hack it if it's not possible out of the box, but I would be happy to get some directions.

And thanks for a great plugin!

Regards,
Mark

**Comment by mpociot** [comment]
Hi Mark,

no - it's currently not possible out of the box and it might be a bit complicated to achieve.

The problem is:

Let's say you have this code:

```php
$page = new Page();
$page->foo = "bar";
$page->save();

$widget = new PageWidget();
$widget->page_id = $page->getKey();
$widget->foo = "baz";
$widget->save();
```

When the package creates the version for the "Page" model, it doesn't know that there are any relations - because they don't exist yet. So when you try to restore the Page model, it doesn't know that it had any relations at all.

So in order to revert all relationships as well, you would need to somehow associate the relationships version_id's to the revertable model.

A simpler approach would be to save the `version_id` of the Page in your PageWidget.

For example:

```php
$page = new Page();
$page->foo = "bar";
$page->save();

$widget = new PageWidget();
$widget->page_version_id = $page->currentVersion()->getKey();
$widget->page_id = $page->getKey();
$widget->foo = "baz";
$widget->save();
```

The important part is to update the `page_version_id` every time you update your widget model.

And when you revert the Page, you'll need to lookup the related widget version with the right version id. Since the model data is serialized, this can't be done in SQL, so there might be a performance issue, depending on how many versions a widget might have.

```php
$previousVersion = $page->previousVersion();
$previousVersion->revert();

$widgets = PageWidget::where( "page_version_id" , $previousVersion->getKey() );
// Revert every widget
foreach( $widgets AS $widget ){
    // Find the version, that points to the correct page version id
    foreach( $widget->versions AS $version )
    {
        if( $version->getModel()->page_version_id == $previousVersion->getKey() )
        {
             $version->revert();
        }
    }
}
```

As I said - this is a pretty hacky approach - but it's the only one I can think of right now.

**Comment by aureliusm** [comment]
Understood.. thanks for pointing me in the right direction.. I will implement it this way with more abstraction so I will be able to reuse it and let you know of the results and if it causes any performance issues or not...
