### ISSUE TITLE
Version Limit

### ISSUE THREAD

**Issue by SteveEdson** [mpociot/versionable#9]
Would it be possible to limit the number of versions that are stored for a model? Alternatively, having  a method to purge items older than X, or after N number of versions.

The limit could be stored on a property of the model.

Apart from that, this package seems great so far, thanks!

**Comment by emilv** [comment]
Which of these would be of interest?

* Purging Versions among all Versionable models older than X
* Purging Versionable versions older than X (one model only)
* Ensuring a maximum of X versions of each object among all Versionable models
* Ensuring a maximum of X versions of each object of one Versionable model

**Comment by SteveEdson** [comment]
Based on my usage, I would say "Purging Versionable versions older than X (per model) ... ensuring a maximum of X versions of this object"

**Comment by mpociot** [comment]
Yes, I also think that it would be great if we could just define a maximum version count per model.

Would you be interested in submitting a PR @emilv ?

**Comment by lukasoppermann** [comment]
Hey, I think this addition would be very useful. However maybe there should be a way to "freeze" certain versions or add 'inbetween' versions.

I am thinking of the following case:

1. You want to store 5 real versions
2. A user is editing a post which saves via ajax auto-saving
3. changing thinks in the text and having it save will overwrite all versions (which is correct behavior)

However what would be good is if you could say:

I once to store 5 versions, which the user explicitly "published" AND I want to save the last 20 versions between the last "published" version and now.

I hope you understand what I mean? For this it would be good to be able to store 2 kinds of versions so that you can limit both kinds and purge them independently. Maybe a simple `type` or `tag` could help for this. Than in the logic for limiting (which will rely on some kind of purge logic, this field can be used to only work with the given versions).
